title: Andrew Hawker
author: Andrew Hawker
email: andrew.r.hawker@gmail.com
description: Personal website of Andrew Hawker
baseurl:
permalink: /:categories/:year/:month/:day/:title/
url: https://andrew.hawker.io
twitter_username: rekwah
github_username:  ahawker

# Jekyll SEO
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
twitter:
  card: summary
  username: rekwah
logo: /assets/images/android-chrome-512x512.png
social:
  name: Andrew Hawker
  links:
  - https://stackoverflow.com/users/84942/ahawker
  - https://github.com/ahawker
  - https://linkedin.com/in/ahawker
  - https://twitter.com/rekwah

# Jekyll Archives
# https://github.com/jekyll/jekyll-archives/blob/master/docs/configuration.md
jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  permalinks:
    year: '/archives/year/:year/'
    tag: '/archives/tag/:name/'
    category: '/archives/category/:name/'
  layout: archive

sass:
  style: compressed

markdown: kramdown

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - README.md
  - Makefile
  - .git
  - .gitignore
  - yarn.lock
  - yarn-error.log
  - node_modules

ga_tracking_id: UA-36365256-1

defaults:
  - scope:
      path: ''
      type: posts
    values:
      image: /assets/images/android-chrome-512x512.png
