title: Andrew Hawker
author: Andrew Hawker
email: andrew.r.hawker@gmail.com
description: Personal website of Andrew Hawker
baseurl:
permalink: /:categories/:year/:month/:day/:title/
url: https://andrew.hawker.io
twitter_username: rekwah
github_username:  ahawker

# Jekyll SEO
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
twitter:
  username: rekwah
logo: /assets/images/android-chrome-512x512.png
social:
  name: Andrew Hawker
  links:
  - https://stackoverflow.com/users/84942/ahawker
  - https://github.com/ahawker
  - https://linkedin.com/in/ahawker
  - https://twitter.com/rekwah

sass:
  style: compressed

markdown: Pandoc

pandoc:
  extensions:
    - section-divs
    - from: 'markdown+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-pandoc
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Makefile
  - .git
  - .gitignore

ga_tracking_id: UA-36365256-1
